/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.managment;

import javax.swing.JOptionPane;

/**
 *
 * @author sabbir
 */
public class PatienInformationEdit extends javax.swing.JFrame {

    /**
     * Creates new form PatienInformationEdit
     */
    public PatienInformationEdit() {
        initComponents();
        ShowInformation();
    }
    
    void ShowInformation(){
        
        ShowProfielName.setText(MainClass.PatientInformation.get(patientInformation.pre).getPatientName());
        ShowProfileUserName.setText(MainClass.PatientInformation.get(patientInformation.pre).getUserName());
        ShowProfileNumber.setText(MainClass.PatientInformation.get(patientInformation.pre).getCont());
        ShowProfileAddress.setText(MainClass.PatientInformation.get(patientInformation.pre).getAdd());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ShowProfilePassword = new javax.swing.JLabel();
        ShowProfielName = new javax.swing.JLabel();
        ShowProfileUserName = new javax.swing.JLabel();
        ShowProfileNumber = new javax.swing.JLabel();
        ShowProfileAddress = new javax.swing.JLabel();
        buttonName = new javax.swing.JButton();
        buttonAddress = new javax.swing.JButton();
        buttonPassword = new javax.swing.JButton();
        buttonNumber = new javax.swing.JButton();
        buttonUser = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name :");

        jLabel2.setText("Number :");

        jLabel3.setText("Address :");

        jLabel4.setText("User Name :");

        jLabel5.setText("Password :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Profile");

        buttonName.setText("Edit");
        buttonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNameActionPerformed(evt);
            }
        });

        buttonAddress.setText("Edit");
        buttonAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddressActionPerformed(evt);
            }
        });

        buttonPassword.setText("Edit");
        buttonPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPasswordActionPerformed(evt);
            }
        });

        buttonNumber.setText("Edit");
        buttonNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumberActionPerformed(evt);
            }
        });

        buttonUser.setText("Edit");
        buttonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUserActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userLayout = new javax.swing.GroupLayout(user);
        user.setLayout(userLayout);
        userLayout.setHorizontalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(userLayout.createSequentialGroup()
                                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(userLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ShowProfilePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ShowProfielName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ShowProfileUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ShowProfileNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonName)
                                            .addComponent(buttonPassword)
                                            .addComponent(buttonNumber)
                                            .addComponent(buttonUser)))
                                    .addGroup(userLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ShowProfileAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonAddress))))))
                    .addGroup(userLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        userLayout.setVerticalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowProfielName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonName))
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShowProfileUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(userLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buttonUser)))
                .addGap(18, 18, 18)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowProfilePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPassword))
                .addGap(17, 17, 17)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowProfileNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonNumber)))
                .addGap(18, 18, 18)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLayout.createSequentialGroup()
                        .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShowProfileAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addComponent(jButton1))
                    .addComponent(buttonAddress))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNameActionPerformed
        String ChangeName =   JOptionPane.showInputDialog(null, "Enter Edit Name : ", "Name Edit", JOptionPane.QUESTION_MESSAGE);
        if( ChangeName != null){
            //  login.set(CustomerInformation.loginNumber, login.get(CustomerInformation.loginNumber));
            MainClass.PatientInformation.get(patientInformation.pre).setPatientName(ChangeName);
            ShowProfielName.setText(  MainClass.PatientInformation.get(patientInformation.pre).getPatientName());
        }
    }//GEN-LAST:event_buttonNameActionPerformed

    private void buttonAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddressActionPerformed
        // TODO add your handling code here:
        String ChangeName =   JOptionPane.showInputDialog(null, "Enter Edit Address : ", "Address Edit", JOptionPane.QUESTION_MESSAGE);
        if( ChangeName != null){
            //  login.set(CustomerInformation.loginNumber, login.get(CustomerInformation.loginNumber));
            MainClass.PatientInformation.get(patientInformation.pre).setAdd(ChangeName);
            ShowProfileAddress.setText(  MainClass.PatientInformation.get(patientInformation.pre).getAdd());
        }
    }//GEN-LAST:event_buttonAddressActionPerformed

    private void buttonPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPasswordActionPerformed
        // TODO add your handling code here:
        String ChangeName =   JOptionPane.showInputDialog(null, "Enter Edit Password : ", "Password Edit", JOptionPane.QUESTION_MESSAGE);
        if( ChangeName != null){
            //  login.set(CustomerInformation.loginNumber, login.get(CustomerInformation.loginNumber));
            MainClass.PatientInformation.get(patientInformation.pre).setPass(ChangeName);
            ShowProfilePassword.setText(  MainClass.PatientInformation.get(patientInformation.pre).getPass());
        }
    }//GEN-LAST:event_buttonPasswordActionPerformed

    private void buttonNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumberActionPerformed
        // TODO add your handling code here:
        String ChangeName =   JOptionPane.showInputDialog(null, "Enter Edit Number : ", "Number Edit", JOptionPane.QUESTION_MESSAGE);
        if( ChangeName != null){
            //  login.set(CustomerInformation.loginNumber, login.get(CustomerInformation.loginNumber));
        MainClass.PatientInformation.get(patientInformation.pre).setCont(ChangeName);
        ShowProfileNumber.setText(  MainClass.PatientInformation.get(patientInformation.pre).getCont());
        }

    }//GEN-LAST:event_buttonNumberActionPerformed

    private void buttonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUserActionPerformed
        // TODO add your handling code here:
//        String ChangeName =   JOptionPane.showInputDialog(null, "Enter Edit UserName : ", "UserName Edit", JOptionPane.QUESTION_MESSAGE);
//        if( ChangeName != null){
//            //  login.set(CustomerInformation.loginNumber, login.get(CustomerInformation.loginNumber));
//            CustomerAccount.sinup.get(CustomerInformation.loginNumber).setuserName(ChangeName);
//            ShowProfileUserName.setText( CustomerAccount.sinup.get(CustomerInformation.loginNumber).userName);
//        }
    }//GEN-LAST:event_buttonUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new PatientHomePage().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatienInformationEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatienInformationEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatienInformationEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatienInformationEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatienInformationEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ShowProfielName;
    private javax.swing.JLabel ShowProfileAddress;
    private javax.swing.JLabel ShowProfileNumber;
    private javax.swing.JLabel ShowProfilePassword;
    private javax.swing.JLabel ShowProfileUserName;
    private javax.swing.JButton buttonAddress;
    private javax.swing.JButton buttonName;
    private javax.swing.JButton buttonNumber;
    private javax.swing.JButton buttonPassword;
    private javax.swing.JButton buttonUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel user;
    // End of variables declaration//GEN-END:variables
}
